name: saucectl cypress tests

on:
  pull_request:
  push:
    branches:
      - master

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Saucectl RUN Docker and Cloud
        uses: saucelabs/saucectl-run-action@v1
        with:
          testing-environment: ""
          concurrency: 10
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install saucectl
        uses: saucelabs/saucectl-run-action@v1
        with:
          skip-run: true
          testing-environment: ""
          concurrency: 10

      - name: Cypress
        run: |
          saucectl run
  report_success:
    runs-on: ubuntu-latest
    needs: cypress
    if: success()
    env:
      SAUCE_URL: ${{format('https://saucelabs.com/rest/v1/{0}/jobs/{1}', env.SAUCE_USERNAME, env.GITHUB_RUN_ID)}}
    steps:
      - name: Send Success to Sauce
        run: |
          curl \
          PUT -X \
          -u env.SAUCE_USERNAME:env.SAUCE_ACCESS_KEY \
          env.SAUCE_URL \
          --header 'Content-Type: application/json' \
          --data-raw \'{"data": { "passed": "true" }}'
  report_failure:
    runs-on: ubuntu-latest
    needs: cypress
    if: failure()
    env:
      SAUCE_URL: ${{format('https://saucelabs.com/rest/v1/{0}/jobs/{1}', env.SAUCE_USERNAME, env.GITHUB_RUN_ID)}}
    steps:
        - name: Send Failure to Sauce
          run: |
            curl \
            PUT -X \
            -u env.SAUCE_USERNAME:env.SAUCE_ACCESS_KEY \
            env.SAUCE_URL \
            --header 'Content-Type: application/json' \
            --data-raw \'{"data": { "passed": "false" }}'
