name: saucectl cypress tests

on:
  pull_request:
  push:
    branches:
      - master

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Saucectl RUN Docker and Cloud
        uses: saucelabs/saucectl-run-action@v1
        with:
          testing-environment: ""
          concurrency: 10
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install saucectl
        uses: saucelabs/saucectl-run-action@v1
        with:
          skip-run: true
          testing-environment: ""
          concurrency: 10

      - name: Cypress
        run: |
          saucectl run

      - name: print env
        run: env

  report_success:
    runs-on: ubuntu-latest
    needs: cypress
    if: success()
    steps:
      - name: Send Success to Sauce
        run: |
          curl \
          PUT -X \
          -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" \
          "https://saucelabs.com/rest/v1/$SAUCE_USERNAME/jobs/$JOB_ID" \
          --header 'Content-Type: application/json' \
          --data-raw '{"data": { "passed": "true" }}'
  report_failure:
    runs-on: ubuntu-latest
    needs: cypress
    if: failure()
    steps:
        - name: Send Failure to Sauce
          run: |
            curl \
            PUT -X \
            -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" \
            "https://saucelabs.com/rest/v1/$SAUCE_USERNAME/jobs/$JOB_ID" \
            --header 'Content-Type: application/json' \
            --data-raw '{"data": { "passed": "false" }}'
